# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstFoodName', models.TextField()),
                ('firstFoodPrice', models.FloatField()),
                ('firstFoodImage', models.TextField(default=None)),
            ],
            options={
                'db_table': 'first_food',
            },
        ),
    ]
