# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondFoodName', models.TextField()),
                ('secondFoodPrice', models.FloatField()),
                ('secondFoodImage', models.TextField(default=None)),
            ],
            options={
                'db_table': 'second_food',
            },
        ),
    ]
