# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField()),
                ('sectionImage', models.TextField()),
            ],
        ),
    ]
