# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0002_bascket_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='foodDay',
            field=models.IntegerField(default=1),
        ),
    ]
