# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0004_auto_20170508_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodday',
            name='foodDayNumber',
            field=models.IntegerField(default=1),
        ),
    ]
