# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0005_foodday_fooddaynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customUserName', models.TextField()),
                ('firstFood', models.TextField()),
                ('secondFood', models.TextField()),
                ('salatFood', models.TextField()),
                ('customDate', models.DateField()),
                ('customPrice', models.FloatField()),
            ],
            options={
                'db_table': 'customFood',
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchaseId',
        ),
        migrations.DeleteModel(
            name='Bascket',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
